import os
import time

def cleanup_files(file_list):
    """
    Safely deletes temporary files. 
    Added a small delay to ensure Windows has released the file handles.
    """
    time.sleep(1) # Wait for 1 second to avoid PermissionErrors
    for file_path in file_list:
        try:
            if os.path.exists(file_path):
                os.remove(file_path)
                print(f"Successfully deleted: {file_path}")
        except PermissionError:
            print(f"Permission Error: Could not delete {file_path}. It might still be in use.")
        except Exception as e:
            print(f"Error during cleanup: {e}")

def generate_report_text(transcript, emotion_results, conf_results):
    """
    Formats all the AI analysis into a clean, readable text string
    that the user can download as a report.
    """
    report = f"""
    =========================================
    AI INTERVIEW PERFORMANCE REPORT
    =========================================
    
    1. TRANSCRIPT:
    -----------------------------------------
    "{transcript}"
    
    2. EMOTION ANALYSIS:
    -----------------------------------------
    - Speech Tone: {emotion_results.get('sentiment', 'N/A')}
    - Sentiment Score: {emotion_results.get('score', 0)}
    
    3. CONFIDENCE METRICS:
    -----------------------------------------
    - Overall Confidence Score: {conf_results.get('score', 0)}/100
    - Speaking Pace: {conf_results.get('wpm', 0)} Words Per Minute
    - Assessment: {conf_results.get('status', 'N/A')}
    
    4. FILLER WORD USAGE:
    -----------------------------------------
    - Total Fillers Detected: {conf_results.get('total_fillers', 'Calculated in transcript')}
    
    =========================================
    Generated by AI Interview Analyzer
    =========================================
    """
    return report